def gen_html(first_bc_name,max_str,min_str,mean_str,total_str,maxlen_str,minlen_str,meanlen_str,img_base,img2_base,img3_base,html2):
    html =  '<!doctype html>'
    html += '<html lang="en" class="no-js">'
    html += ' <head>'
    html += ' <meta charset="utf-8">'
    html += ' <meta http-equiv="x-ua-compatible" content="ie=edge">'
    html += ' <meta name="viewport" content="width=device-width, initial-scale=1.0">'
    html += ' <link rel="canonical" href="https://html5-templates.com/demo/infinite-scroll-image-gallery/" />'
    html += '     <title>To The Moon Project</title>'
    html += '     <meta name="description" content="A brief page description">'
    html += '     <link rel="stylesheet" href="style.css">'
    html += ' 	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>'
    html += '     <script src="script.js"></script>'
    html += ' 	<style>'
    html += ' 		table {'
    html += ' 		  font-family: arial, sans-serif;'
    html += ' 		  border-collapse: collapse;'
    html += ' 		  width: 100%;'
    html += ' 		}		'
    html += ' 		td, th {'
    html += ' 		  border: 1px solid #dddddd;'
    html += ' 		  text-align: left;'
    html += ' 	  padding: 8px;'
    html += ' 		}'		
    html += ' 		tr:nth-child(even) {'
    html += ' 		  background-color: #dddddd;'
    html += ' 		}'
    html += ' 		</style>'
    html += ' </head>'
    html += ' <body>'
    html += ' 	<p>&nbsp;</p>'
    html += ' 	<h1>To The Moon Project</h1>'
    html += ' 	<p style="padding: 10px 20px; text-align: center;">FASTQ Read Analysis Report.</p>'
    html += ' 	<p style="padding: 10px 20px; text-align: center;">Summary of read length and Qscores</p>'
    html += ' 	<table>'
    html += ' 		<tr>'
    html += ' 		  <th>Barcode</th>'
    html += ' 		  <th>Total Reads</th>'
    html += ' 		  <th>Max(Qscore)</th>'
    html += ' 		  <th>Min(Qscore)</th>'
    html += ' 		  <th>Mean(Qscore)</th>'
    html += ' 		  <th>Max(length)</th>'
    html += ' 		  <th>Min(length)</th>'
    html += ' 		  <th>Mean(length)</th>'
    html += ' 		</tr>'
    html += ' 		<tr>'
    html += ' 		  <td>'+first_bc_name+'</td>'
    html += ' 		  <td>'+total_str+'</td>'
    html += ' 		  <td>'+max_str+'</td>'
    html += ' 		  <td>'+min_str+'</td>'
    html += ' 		  <td>'+mean_str+'</td>'
    html += ' 		  <td>'+maxlen_str+'</td>'
    html += ' 		  <td>'+minlen_str+'</td>'
    html += ' 		  <td>'+meanlen_str+'</td>'
    html += ' 		</tr>'   
    html += html2
    html += ' 	  </table>'
    html += ' 	<div id="gallery">	'    
    html += " 	<center>	<img src='data:image/png;base64," + img_base + "'/> 	<img src='data:image/png;base64," + img2_base + "'/><img src='data:image/png;base64," +                      img3_base + "'/></center>"
   
    html += ' 	</div>'

  
    html += ' </body>'
    html += ' </html>'
    return html